server:
  port: 8079

spring:
  application:
    name: api-monolith

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        presigned-url-duration: ${S3_PRESIGNED_URL_DURATION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}

  kafka:
    bootstrap-servers: ${KAFKA_IP}
    producer:
      acks: all
      retries: 10
      batch-size: 32768
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        linger.ms: 5
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: memberRegisterEvent:MeshX.HypeLink.common.kafka.MemberRegisterEvent,dataSyncEvent:MeshX.HypeLink.common.kafka.DataSyncEvent

jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration-ms: ${JWT_ACCESS}
  refresh-token-expiration-ms: ${JWT_REFRESH}

portone:
  api:
    secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}

naver:
  api:
    client-id: ${NAVER_MAP_CLIENT}
    client-secret: ${NAVER_MAP_SECRET}

websocket:
  allowed-origin: ${SERVER}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics  # 필요 시 "*" 로 전체 공개
      base-path: /api/health     # 기본값 (원하면 /api/health 로 커스터마이징 가능)
  endpoint:
    health:
      show-details: always     # 상세 상태 보기 (디버깅에 유용)
      group:
        core:
          include:
            - db
            - redis
            - diskSpace
            - ssl
  metrics:
    tags:
      application: hypelink

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    # Swagger UI가 로드할 메인 문서 지정 (Petstore fallback 방지)
    url: /api/v3/api-docs
    # 여러 스펙을 쓰고 싶다면 urls 목록으로도 가능 (선택)
    urls:
      - name: HypeLink API
        url: /api/v3/api-docs
    # api-docs path를 바꿨으니 config-url도 맞춰줌 (명시 권장)
    config-url: /api/v3/api-docs/swagger-config

eureka:
#  instance:
#    prefer-ip-address: false
#    hostname: api-monolith # hypelink-monolith-svc          # K8s Service 이름
  client:
    service-url:
      defaultZone: ${API_DISCOVERY_SERVICE}
    registerWithEureka: true
    fetchRegistry: true

kafka:
  topic:
    item: ${KAFKA_ITEM_TOPIC}
    itemDetail: ${KAFKA_ITEM_DETAIL_TOPIC}
    category: ${KAFKA_CATEGORY_TOPIC}
    size: ${KAFKA_SIZE_TOPIC}
    color: ${KAFKA_COLOR_TOPIC}
    transaction:
      item:
        save: ${KAFKA_ITEM_TRANSACTION_SAVE_TOPIC}
        rollback: ${KAFKA_ITEM_TRANSACTION_ROLLBACK_TOPIC}
      itemDetail:
        save: ${KAFKA_ITEM_DETAIL_TRANSACTION_SAVE_TOPIC}
        rollback: ${KAFKA_ITEM_DETAIL_TRANSACTION_ROLLBACK_TOPIC}
