eureka:
  instance:
    prefer-ip-address: false
    hostname: hypelink-gateway-svc          # ✅ K8s Service 이름
  client:
    service-url:
      defaultZone: ${API_DISCOVERY_SERVICE}
    registerWithEureka: true
    fetchRegistry: true

jwt:
  secret-key: ${JWT_KEY}

management:
  endpoints:
    web:
      base-path: /api/health    # actuator의 기본 경로를 변경
      exposure:
        include: health,info    # 노출시킬 엔드포인트 지정

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${AUTH_REDIS_URL}
      port: ${AUTH_REDIS_PORT}

  cloud:
    gateway:
      server:
        webflux:
          routes:
#            - id: api-item
#              uri: ${ITEM_SERVICE_URI}
#              order: 1
#              predicates:
#                - Path=/api/item/**
            - id: api-monolith
              uri: ${MONOLITH_SERVICE_URI}
              order: 1
              predicates:
                - Path=/api/**

#                - StripPrefix=1     # ?? 1
#                - RewritePath=/user/(?<remaining>.*), /${remaining} # ?? 2