eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    registerWithEureka: false
    fetchRegistry: true

jwt:
  secret-key: ${JWT_KEY}

# Circuit Breaker 설정 (Resilience4j)
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
    instances:
      authService:
        base-config: default

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${AUTH_REDIS_URL}
      port: ${AUTH_REDIS_PORT}

  cloud:
    gateway:
      server:
        webflux:
          routes:
#            - id: api-direct
#              uri: lb://api-direct
#              predicates:
#                - Path=/api/store/**
#            - id: api-item
#              uri: lb://api-item
#              predicates:
#                - Path=/api/item/**
#            - id: api-purchase
#              uri: lb://api-purchase
#              predicates:
#                - Path=/api/purchase/**
#            - id: api-auth
#              uri: lb://api-auth
#              predicates:
#                - Path=/api/auth/**

#                - StripPrefix=1     # ?? 1
#                - RewritePath=/user/(?<remaining>.*), /${remaining} # ?? 2