eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    registerWithEureka: false
    fetchRegistry: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
#            - id: api-direct
#              uri: lb://api-direct
#              predicates:
#                - Path=/api/store/**
#            - id: api-item
#              uri: lb://api-item
#              predicates:
#                - Path=/api/item/**
#            - id: api-purchase
#              uri: lb://api-purchase
#              predicates:
#                - Path=/api/purchase/**
#            - id: api-auth
#              uri: lb://api-auth
#              predicates:
#                - Path=/api/auth/**

#                - StripPrefix=1     # ?? 1
#                - RewritePath=/user/(?<remaining>.*), /${remaining} # ?? 2